### PR TITLE
Support Go modules

### PR DESCRIPTION
**Pull request by tekkamanendless**
This adds support for Go modules.  Because this package is already at version 2.4, we can't just directly add `go.mod` and `go.sum`; instead, we need to bump the version to 3.0.0 and namespace the module with `/v3`.  Remember, Go modules require a `/vN` namespace for every version greater than 1.  Because we're already midway through version 2, I think that the best course of action would be to introduce Go modules in a new major version.

Once merged, this should be tagged as `v3.0.0`.  If needed, subsequent work on the version 2 train should be done in a `v2` branch made from the commit before this one.

### CODE REVIEW

**Comment by tmc** [comment]
@tekkamanendless can you fix these conflicts?

**Comment by tekkamanendless** [comment]
Fixed!

**Comment by tmc** [comment]
@kevinburke hi Kevin! Do you have thoughts here?

**Comment by kevinburke** [comment]
Hey, this isn't something I'm interested in merging or supporting right now.

**Pull request closed without merging**
