### PR TITLE
add delete message method

### PR DESCRIPTION
**Pull request by kgolding**

### CODE REVIEW

**Comment by kevinburke** [comment]
Thanks for this - can we merge it without changing go-types from kevinburke to kgolding? If there was a reason you had to do that I'm happy to look at changes to that library.

**Comment by kevinburke** [comment]
Does that change just get rid of the mongo dependency? I might just rip that out.

**Comment by kgolding** [comment]
The second commit is my first attempt at slimming it down removing mgo

**Comment by kevinburke** [comment]
ok, please open another PR or issue against github.com/kevinburke/go-types, we can merge that change separately from this one.

**Comment by kevinburke** [comment]
I'm happy to merge the Delete Message change but I think we should discuss and merge the binary stripping/size stuff in a different PR. I can just cherry pick it, let me know.

**Comment by kgolding** [comment]
Will resubmit just the add delete message change and close this PR

**Pull request closed without merging**
